# Shared config

export ZSH=$HOME/.zsh
export HISTFILE=$ZSH/.zsh_history
export HISTSIZE=20000 # size of history file
export SAVEHIST=20000 # how many lines to save
setopt HIST_IGNORE_ALL_DUPS # history won't save duplicates
setopt HIST_FIND_NO_DUPS # history won't show duplicates on search

### PLUGINS & COMPLETIONS

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
source $ZSH/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fpath=($ZSH/plugins/zsh-completions/src $fpath)

### THEME

eval "$(oh-my-posh init zsh --config $DOTFILES/oh-my-posh/hearthside.omp.yaml)"

### ALIASES

alias ga="git add"
alias gc="git commit"
alias gco="git checkout"
alias grb="git rebase"
alias gs="git status"

# Functions

gfo() {
  git fetch origin $1:$1
}

# Keybinds

# Ctrl + up/down to search matching history
bindkey '^[[1;5A' history-beginning-search-backward
bindkey '^[[1;5B' history-beginning-search-forward
# Ctrl + Left/Right arrow to skip words
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
# Ctrl + Backspace to delete the previous word
bindkey '^H' backward-kill-word


# Sources OS-specific files if they exist

export DOTFILES=$HOME/Projects/dotfiles
OS_FILE="$DOTFILES/zsh/zshrc-$(uname -s)"
if [ -f "$OS_FILE" ]; then
  source "$OS_FILE"
fi

